// Generated by scripts/generate-icons.cjs; runtime has no SVG dependency.
export const ICON_ASSETS = {
  archive: {
    24: require("../../assets/icons/time80-a-v1/png/archive-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/archive-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/archive-32.png"),
  },
  check: {
    24: require("../../assets/icons/time80-a-v1/png/check-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/check-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/check-32.png"),
  },
  commute: {
    24: require("../../assets/icons/time80-a-v1/png/commute-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/commute-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/commute-32.png"),
  },
  edit: {
    24: require("../../assets/icons/time80-a-v1/png/edit-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/edit-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/edit-32.png"),
  },
  exercise: {
    24: require("../../assets/icons/time80-a-v1/png/exercise-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/exercise-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/exercise-32.png"),
  },
  family: {
    24: require("../../assets/icons/time80-a-v1/png/family-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/family-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/family-32.png"),
  },
  grid: {
    24: require("../../assets/icons/time80-a-v1/png/grid-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/grid-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/grid-32.png"),
  },
  home: {
    24: require("../../assets/icons/time80-a-v1/png/home-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/home-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/home-32.png"),
  },
  more: {
    24: require("../../assets/icons/time80-a-v1/png/more-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/more-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/more-32.png"),
  },
  plus: {
    24: require("../../assets/icons/time80-a-v1/png/plus-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/plus-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/plus-32.png"),
  },
  report: {
    24: require("../../assets/icons/time80-a-v1/png/report-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/report-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/report-32.png"),
  },
  rest: {
    24: require("../../assets/icons/time80-a-v1/png/rest-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/rest-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/rest-32.png"),
  },
  settings: {
    24: require("../../assets/icons/time80-a-v1/png/settings-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/settings-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/settings-32.png"),
  },
  study: {
    24: require("../../assets/icons/time80-a-v1/png/study-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/study-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/study-32.png"),
  },
  work: {
    24: require("../../assets/icons/time80-a-v1/png/work-24.png"),
    30: require("../../assets/icons/time80-a-v1/png/work-30.png"),
    32: require("../../assets/icons/time80-a-v1/png/work-32.png"),
  },
};
export const ICON_COLORS = {
  archive: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  check: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  commute: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  edit: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  exercise: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  family: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  grid: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  home: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  more: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  plus: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  report: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  rest: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  settings: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  study: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
  work: {
    background: "#F3E2D5",
    foreground: "#302E2A",
  },
};
