const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { Resvg } = require("@resvg/resvg-js");
const root = path.join(__dirname, "../assets/icons/time80-a-v1");
const hash = (s) => crypto.createHash("sha256").update(s).digest("hex");
const originals = JSON.parse(
  fs.readFileSync(path.join(root, "source-hashes.json")),
).files;
const output = {},
  registry = [],
  colors = {};
fs.mkdirSync(path.join(root, "png"), { recursive: true });
for (const file of Object.keys(originals).sort()) {
  const original = fs.readFileSync(path.join(root, "svg", file));
  if (hash(original) !== originals[file])
    throw Error(`Approved SVG changed: ${file}`);
  const svg = original.toString();
  const match = svg.match(/(<svg\b[^>]*>\s*)<rect\b([^>]*)\/?>(?:<\/rect>)?/);
  if (!match) throw Error(`First background rect missing: ${file}`);
  const bg = match[2].match(/fill="([^"]+)"/)[1];
  const fg = svg.replace(match[0], match[1]);
  const stroke = fg.match(/stroke="([^"]+)"/)?.[1] ?? "#302E2A";
  const key = file.replace("duo-", "").replace(".svg", "");
  colors[key] = { background: bg, foreground: stroke };
  for (const size of [24, 30, 32])
    for (const density of [1, 2, 3, 4]) {
      const name = `${key}-${size}${density === 1 ? "" : `@${density}x`}.png`;
      const png = new Resvg(fg, {
        fitTo: { mode: "width", value: size * density },
      })
        .render()
        .asPng();
      if (process.argv.includes("--check")) {
        if (
          !fs.existsSync(path.join(root, "png", name)) ||
          !fs.readFileSync(path.join(root, "png", name)).equals(png)
        )
          throw Error(`Nonreproducible PNG: ${name}`);
      } else fs.writeFileSync(path.join(root, "png", name), png);
      output[name] = hash(png);
    }
  registry.push(
    `  ${key}: {24: require('../../assets/icons/time80-a-v1/png/${key}-24.png'),30: require('../../assets/icons/time80-a-v1/png/${key}-30.png'),32: require('../../assets/icons/time80-a-v1/png/${key}-32.png')},`,
  );
}
const unformatted = `// Generated by scripts/generate-icons.cjs; runtime has no SVG dependency.\nexport const ICON_ASSETS = {\n${registry.join("\n")}\n};\nexport const ICON_COLORS = ${JSON.stringify(colors, null, 2)};\n`;
(async () => {
  const source = await require("prettier").format(unformatted, {
    parser: "typescript",
  });
  const target = path.join(__dirname, "../src/icons/iconAssets.ts");
  if (process.argv.includes("--check")) {
    if (fs.readFileSync(target, "utf8") !== source)
      throw Error("Icon registry changed");
  } else {
    fs.writeFileSync(target, source);
    fs.writeFileSync(
      path.join(root, "generated-hashes.json"),
      JSON.stringify(
        { generator: "@resvg/resvg-js@2.6.2", files: output },
        null,
        2,
      ) + "\n",
    );
  }
  console.log(
    `Verified 15 approved icons, ${Object.keys(output).length} PNG variants`,
  );
})().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
